### ISSUE TITLE
Minimizer setup documentation

### ISSUE THREAD

**Issue by TOFarmer** [QENSlibrary/QENSmodels#14]
**Is your feature request related to a problem? Please describe.**
I wonder if we want to include a little more detail about the parameters we are passing to the minimizers, in order to assist users who are unfamiliar with bumps/lmfit/scipy.

**Describe the solution you'd like**
To save having to provide essentially the same comments in every notebook, potentially one example for each minimizer could be selected (e.g. Brownian Translation for bumps, Lorentzian for lmfit) where some additional comments could be included e.g.

```
# Comment could be added explaining exactly what bmp.Curve does and what the parameters are
Mq = bmp.Curve(model_convol, hw, sqw[:,i], err[:,i], q=q[i],
           scale=1000, center=0.0, D=0.1, resolution=res[:, I])
```

An additional line could be added to 'Introduction.ipynb' or 'Summary of the Jupyter notebooks.ipynb' mentioning the examples which contain more comments about the minimizer setup.

**Comment by celinedurniak** [comment]
Solved in #34
