### ISSUE TITLE
Numerical problem with the analytical definition of Gaussian and Lorentzian for very narrow functions

### ISSUE THREAD

**Issue by gonzalezma** [QENSlibrary/QENSmodels#24]
The analytical definition of the standard Gaussian and Lorentzian functions is such that the integral between -inf and inf is 1. However, numerically this breaks when the width of the function becomes smaller than the bin width (dx), as the function sampling is too coarse to define a Gaussian or Lorentzian function. 

When the function width is very small, it becomes essentially a delta function, but with a value at x=0 that is much larger than the corresponding value for the delta, which is defined as 1/dx. As a result, a numerical integration of the narrow Gaussian or Lorentzian will give a value > 1, which is incorrect.

Proposed solution: Check the integral of the Gaussian/Lorentzian before scaling, and if > 1 then use this value to normalize the function before multiplying by the scale factor.

Note that the normalization by area should not be done by default, because having a value < 1 is correct as our x range does not extend from -inf to inf.

**Comment by celinedurniak** [comment]
Done with #26
